name: OSS Review Toolkit Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download ORT
        run: |
          curl -sLO https://github.com/oss-review-toolkit/ort/releases/latest/download/ort.jar
      - name: Run ORT
        run: java -jar ort.jar analyze -i . -o ort-results
