name: Talisman Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  talisman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install talisman
        run: |
          wget https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64
          chmod +x talisman_linux_amd64
          sudo mv talisman_linux_amd64 /usr/local/bin/talisman
      - name: Run talisman
        run: talisman --scan
